DATASET:
  NAME: "DomainNetDG"
  SOURCE_DOMAINS: ["clipart", "infograph", "painting", "quickdraw", "sketch"]
  SOURCE_DOMAINS_0: ["clipart"]
  SOURCE_DOMAINS_1: ["infograph"]
  SOURCE_DOMAINS_2: ["painting"]
  SOURCE_DOMAINS_3: ["quickdraw"]
  SOURCE_DOMAINS_4: ["sketch"]
  TARGET_DOMAINS: ["real"]