DATASET:
  NAME: "DomainNetDG"
  SOURCE_DOMAINS: ["infograph", "painting", "quickdraw", "real", "sketch"] 
  SOURCE_DOMAINS_0: ["infograph"]
  SOURCE_DOMAINS_1: ["painting"]
  SOURCE_DOMAINS_2: ["quickdraw"]
  SOURCE_DOMAINS_3: ["real"]
  SOURCE_DOMAINS_4: ["sketch"]
  TARGET_DOMAINS: ["clipart"]