DATASET:
  NAME: "OfficeHomeDG"
  SOURCE_DOMAINS: ["art", "clipart", "product"]
  SOURCE_DOMAINS_0: ["art"]
  SOURCE_DOMAINS_1: ["clipart"]
  SOURCE_DOMAINS_2: ["product"]
  TARGET_DOMAINS: ["real_world"]