DATASET:
  NAME: "OfficeHomeDG"
  SOURCE_DOMAINS: ["art", "clipart", "real_world"]
  SOURCE_DOMAINS_0: ["art"]
  SOURCE_DOMAINS_1: ["clipart"]
  SOURCE_DOMAINS_2: ["real_world"]
  TARGET_DOMAINS: ["product"]
