DATASET:
  NAME: "PACS"
  SOURCE_DOMAINS: ["art_painting", "cartoon", "sketch"]
  SOURCE_DOMAINS_0: ["art_painting"]
  SOURCE_DOMAINS_1: ["cartoon"]
  SOURCE_DOMAINS_2: ["sketch"]
  TARGET_DOMAINS: ["photo"]
